# Generated by Django 4.0.2 on 2022-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250)),
                ("artist", models.CharField(max_length=250)),
                ("duration", models.FloatField()),
                ("last_play", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
